AtlasOfLivingAustralia/species-lists

lists-service/src/main/java/au/org/ala/listsapi/AuthMachineJwt.java
lists-service/src/main/java/au/org/ala/listsapi/AuthMachineJwtConfiguration.java
lists-service/src/main/java/au/org/ala/listsapi/controller/GraphQLController.java
lists-service/src/main/java/au/org/ala/listsapi/model/RESTSpeciesListQuery.java
lists-service/src/main/java/au/org/ala/listsapi/service/MigrateService.java
lists-service/src/main/resources/application.properties
lists-ui/README.md
lists-ui/src/App.tsx

See issue https://github.com/AtlasOfLivingAustralia/species-lists/issues/65

migration work

---

cicd/backend/config.ini
cicd/backend/pipeline/deploy_lists_buildspec.yaml
config.ini
lists-service/helm/config/lists-service-config.properties
lists-service/helm/templates/config.yaml
lists-service/helm/values.yaml

Merging your changes here Bruce. I've referenced the secrets, I'll add them to secrets manager manually for now

CICD - added config for new lists service parameters

---

lists-service/src/main/java/au/org/ala/listsapi/service/TaxonService.java

- Temporarily disabled distinct species list item calculation (for now)

Fix optimistic lock error

---

cicd/base/app/base.yaml

client_creds server2server auth flow

---

lists-service/helm/config/lists-service-config.properties

This reverts commit 1df127e5b7e2f1160f1b407f2f146c04d9b268fa.

Revert "Added webservice client ID & secret template to helm config"

---

lists-service/helm/templates/config.yaml

As per https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables

remove the _ from secret names to match properties names

---

lists-service/config/lists-service-config.properties
lists-ui/README.md
lists-ui/config/.env.development
lists-ui/package.json
lists-ui/src/App.tsx
lists-ui/src/Router.tsx
lists-ui/src/helpers/index.ts
lists-ui/src/helpers/utils/parseAsFilters.ts
lists-ui/src/views/Home/index.tsx
lists-ui/src/views/List/components/SpeciesItemDrawer/components/Create.tsx
lists-ui/src/views/List/components/SpeciesItemDrawer/components/Display.tsx
lists-ui/src/views/List/components/SpeciesItemDrawer/components/Edit.tsx
lists-ui/src/views/List/components/SpeciesItemDrawer/index.tsx
lists-ui/src/views/List/index.tsx
lists-ui/yarn.lock

Feature/search param state using URL

---

lists-ui/package-lock.json
lists-ui/package.json
lists-ui/src/App.tsx
lists-ui/src/views/Home/components/ListRow.tsx
lists-ui/yarn.lock

#255 - [see comment](https://github.com/AtlasOfLivingAustralia/species-lists/issues/255#issuecomment-2759945778)

Fix for build failure

---

cicd/backend/pipeline/deploy_lists_buildspec.yaml
lists-service/README.md
lists-service/src/main/java/au/org/ala/listsapi/WebConfig.java
lists-ui/README.md

#319 CORS settings for backend

---

lists-ui/src/views/List/components/SpeciesItemDrawer/components/Display.tsx

#274 Fixed italics for scientific name & genus for species popout

---

lists-service/src/main/java/au/org/ala/listsapi/controller/ElasticUtils.java
lists-service/src/main/java/au/org/ala/listsapi/controller/GraphQLController.java
lists-ui/src/components/FiltersSection.module.css
lists-ui/src/components/FiltersSection.tsx
lists-ui/src/locale/en.json

311 filters UI allow multiple filters

---

lists-service/src/main/java/au/org/ala/listsapi/controller/ElasticUtils.java
lists-ui/src/components/FiltersSection.tsx

244 speciesListItems REST endpoint - fields treated as OR 

---

lists-service/src/main/java/au/org/ala/listsapi/WsToV1RedirectFilter.java
lists-service/src/main/java/au/org/ala/listsapi/controller/AdminController.java
lists-service/src/main/java/au/org/ala/listsapi/controller/ElasticUtils.java
lists-service/src/main/java/au/org/ala/listsapi/controller/RESTController.java

#244 Fix for [issues found in testing](https://github.com/AtlasOfLivingAustralia/species-lists/issues/244#issuecomment-2843875144) original PR by @temi

#244 fix testing issues

---

lists-service/src/main/java/au/org/ala/listsapi/controller/AuthUtils.java
lists-ui/config/.env.development
lists-ui/config/.env.production
lists-ui/config/.env.staging
lists-ui/config/.env.testing
lists-ui/src/Router.tsx
lists-ui/src/locale/en.json
lists-ui/src/views/Admin/index.tsx
lists-ui/src/views/Dashboard/components/Breadcrumbs.tsx
lists-ui/src/views/List/index.tsx
lists-ui/src/views/Reingest/index.tsx

#348 fix reingest list page

---

lists-ui/src/components/FileUploadDropzone.module.css
lists-ui/src/components/FileUploadDropzone.tsx
lists-ui/src/locale/en.json
lists-ui/src/views/Reingest/index.tsx
lists-ui/src/views/Upload/index.tsx

#289 Help doco added to upload and reingest

---

lists-service/src/main/java/au/org/ala/listsapi/controller/IngressController.java
lists-service/src/main/java/au/org/ala/listsapi/controller/RESTController.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListPage.java

#243 specieslistbyguid to return same format as legacy endpoint

---

lists-ui/src/components/FileUploadDropzone.module.css
lists-ui/src/components/FileUploadDropzone.tsx
lists-ui/src/locale/en.json

#298 Improvements to upload/reingest form

---

lists-service/helm/config/constraints.json
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListItem.java
lists-service/src/main/java/au/org/ala/listsapi/service/TaxonService.java

#295 add backwards compatibility for names matching 

---

lists-service/src/main/java/au/org/ala/listsapi/controller/AuthUtils.java
lists-service/src/main/java/au/org/ala/listsapi/controller/GraphQLController.java
lists-service/src/main/java/au/org/ala/listsapi/controller/LegacyController.java
lists-service/src/main/java/au/org/ala/listsapi/controller/RESTController.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListIndex.java
lists-service/src/main/java/au/org/ala/listsapi/service/SearchHelperService.java
lists-service/src/main/java/au/org/ala/listsapi/service/TaxonService.java
lists-service/src/main/java/au/org/ala/listsapi/service/UploadService.java
lists-service/src/main/java/au/org/ala/listsapi/util/ElasticUtils.java
lists-service/src/main/resources/application.properties
lists-service/src/test/java/au/org/ala/listsapi/controller/AuthUtilsTest.java
lists-ui/src/views/Admin/index.tsx
lists-ui/yarn.lock

#368 private lists filter bug

---

lists-service/src/main/java/au/org/ala/listsapi/controller/GraphQLController.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesList.java
lists-service/src/main/java/au/org/ala/listsapi/util/ElasticUtils.java
lists-ui/src/components/ListMeta.tsx

317 public private UI is confusing

---

lists-service/src/main/java/au/org/ala/listsapi/controller/LegacyController.java
lists-service/src/main/java/au/org/ala/listsapi/controller/RESTController.java

#398 Added missing legacy service, added auth check for existing ones

---

lists-service/src/main/java/au/org/ala/listsapi/controller/LegacyController.java
lists-service/src/main/java/au/org/ala/listsapi/model/ErrorResponse.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListItem.java

#398 Added `/v1/speciesListItemsInternal` endpoint

#398 add missing endpoint needed for alerts

---

lists-service/src/main/java/au/org/ala/listsapi/controller/LegacyController.java
lists-service/src/main/java/au/org/ala/listsapi/model/Classification.java
lists-service/src/main/java/au/org/ala/listsapi/model/KvpValueVersion1.java
lists-service/src/main/java/au/org/ala/listsapi/model/QueryListItemVersion1.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListIndex.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListItem.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListItemVersion1.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListPageVersion1.java
lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListVersion1.java
lists-service/src/main/java/au/org/ala/listsapi/repo/SpeciesListCustomRepository.java
lists-service/src/main/java/au/org/ala/listsapi/repo/SpeciesListMongoRepository.java
lists-service/src/main/java/au/org/ala/listsapi/service/BiocacheService.java
lists-service/src/main/java/au/org/ala/listsapi/service/SpeciesListLegacyService.java
lists-service/src/main/java/au/org/ala/listsapi/util/SpeciesListTransformer.java
lists-ui/src/views/List/components/Actions.tsx

#434 fix rest apis following testing

---

lists-service/src/main/java/au/org/ala/listsapi/controller/GraphQLController.java
lists-service/src/main/java/au/org/ala/listsapi/service/TaxonService.java
lists-service/src/main/resources/graphql/schema.graphqls
lists-ui/src/api/queries.ts
lists-ui/src/components/FiltersSection.tsx
lists-ui/src/locale/en.json
lists-ui/src/views/List/components/Actions.tsx
lists-ui/src/views/List/components/Table/TrItem.tsx
lists-ui/src/views/List/index.tsx

#437 include unrecognised taxa count

---

lists-service/src/main/java/au/org/ala/listsapi/model/SpeciesListIndex.java
lists-ui/src/locale/en.json
lists-ui/src/views/Dashboard/index.tsx
lists-ui/src/views/Home/components/ListRow.tsx

fixes for missing flags in results list,
SPATIAL_PORTAL type i18n
revert redirect_url param

#452 UI fixes

---

lists-service/src/main/java/au/org/ala/listsapi/ListsApiApplication.java
lists-service/src/main/java/au/org/ala/listsapi/SecurityConfig.java
lists-service/src/main/java/au/org/ala/listsapi/controller/AdminController.java
lists-service/src/main/java/au/org/ala/listsapi/controller/GraphQLController.java
lists-service/src/main/java/au/org/ala/listsapi/service/UploadService.java
lists-ui/src/views/Admin/index.tsx

#443
Reverted previous changes for this issue and made 1 line change for version to be init as `0` and not `null`.

#443 editing fix take 2

---

lists-ui/config/.env.development
lists-ui/config/.env.testing
lists-ui/src/views/List/components/Actions.tsx

#458 
Also updated config for test servers

#458 Fix for private authoritative lists Biocache links

---

lists-service/src/main/java/au/org/ala/listsapi/WsToV1RedirectFilter.java

Add params to redirected URLs
